version: "3"

services:
  client:
    container_name: online-shop-client
    build:
      context: ./client
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
