version: '3'

services:
  client:
    container_name: online-shop-client
    build:
      context: ./client
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    depends_on:
      - back-end

  back-end:
    container_name: backend
    build:
      context: ./server
      target: development
    environment:
      - POSTGRES_PASSWORD=devpassword
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: postgres-database
    environment:
      - POSTGRES_PASSWORD=devpassword
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
